version: '3'
services:
  frontend:
    build:
      context: ./Techdome-frontend  
      dockerfile: Dockerfile        # The Dockerfile inside the frontend folder
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./Techdome-backend  # Path to the backend folder
      dockerfile: Dockerfile        # The Dockerfile inside the backend folder
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_PORT=27017
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - db-data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
